//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRCChallenge.MatrixOperationsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatrixOperationsService.IMatrixOperationsService")]
    public interface IMatrixOperationsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixOperationsService/CalcDeterminant", ReplyAction="http://tempuri.org/IMatrixOperationsService/CalcDeterminantResponse")]
        HRCChallenge.WebService.Responses.MatrixDeterminantResponse CalcDeterminant(int[] matrix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixOperationsService/CalcDeterminant", ReplyAction="http://tempuri.org/IMatrixOperationsService/CalcDeterminantResponse")]
        System.Threading.Tasks.Task<HRCChallenge.WebService.Responses.MatrixDeterminantResponse> CalcDeterminantAsync(int[] matrix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixOperationsService/FilterAndOrderValues", ReplyAction="http://tempuri.org/IMatrixOperationsService/FilterAndOrderValuesResponse")]
        string FilterAndOrderValues(int[] matrix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixOperationsService/FilterAndOrderValues", ReplyAction="http://tempuri.org/IMatrixOperationsService/FilterAndOrderValuesResponse")]
        System.Threading.Tasks.Task<string> FilterAndOrderValuesAsync(int[] matrix);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatrixOperationsServiceChannel : HRCChallenge.MatrixOperationsService.IMatrixOperationsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatrixOperationsServiceClient : System.ServiceModel.ClientBase<HRCChallenge.MatrixOperationsService.IMatrixOperationsService>, HRCChallenge.MatrixOperationsService.IMatrixOperationsService {
        
        public MatrixOperationsServiceClient() {
        }
        
        public MatrixOperationsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatrixOperationsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatrixOperationsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatrixOperationsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HRCChallenge.WebService.Responses.MatrixDeterminantResponse CalcDeterminant(int[] matrix) {
            return base.Channel.CalcDeterminant(matrix);
        }
        
        public System.Threading.Tasks.Task<HRCChallenge.WebService.Responses.MatrixDeterminantResponse> CalcDeterminantAsync(int[] matrix) {
            return base.Channel.CalcDeterminantAsync(matrix);
        }
        
        public string FilterAndOrderValues(int[] matrix) {
            return base.Channel.FilterAndOrderValues(matrix);
        }
        
        public System.Threading.Tasks.Task<string> FilterAndOrderValuesAsync(int[] matrix) {
            return base.Channel.FilterAndOrderValuesAsync(matrix);
        }
    }
}
